### ISSUE TITLE
希望适配小米Wi-Fi放大器Pro

### ISSUE THREAD

**Issue by 2861164410** [CikeyQi/mijia-plugin#1]
设备列表 ===
┏ 设备名称：小米Wi-Fi放大器Pro
┣ 设备型号：xiaomi.repeater.v3
┗ 设备状态：在线

**Comment by CikeyQi** [comment]
该设备官方没有给可用接口：https://home.miot-spec.com/spec?type=urn:miot-spec-v2:device:repeater:0000A037:xiaomi-v3:1
