### ISSUE TITLE
有提供AIID接口的控制吗 还请大佬答复

### ISSUE THREAD

**Issue by zhou-hack** [CikeyQi/mijia-plugin#2]
在看一些设备的时候能看到AIID接口 但是不知道是否传入数据 烦请大佬答复
![image](https://github.com/CikeyQi/mijia-plugin/assets/84661666/ac3cae38-8e42-4373-9bb5-2b9518fbec82)

**Comment by CikeyQi** [comment]
目前还没看懂AIID方法怎么使用，如果知道的话可以与我联系添加
