### ISSUE TITLE
希望大佬适配下空气净化器

### ISSUE THREAD

**Issue by hnyqwq** [CikeyQi/mijia-plugin#3]
[小米米家空气净化器2S](https://home.miot-spec.com/s/zhimi.airpurifier.ma2)
自己照着写了一个写得比较抽象，且放入文件夹后机器人提示“暂不支持该设备，请将型号为 zhimi.airpurifier.ma2 的适配器文件放入adapter文件夹”，求大佬帮助适配

actionable:
  - name: ["开关"]
    desc: "空气净化器开关，可用值：开、关"
    siid: 2
    piid: 1
    value_regexp: '/(开|关)/g'
  - name: ["模式"]
    desc: "更换模式，可用值：0 - 自动 / 1 - 睡眠 / 2 - 最爱"
    siid: 2
    piid: 2
    value_regexp: '/([0-2])/g'
  - name: ["屏幕开关"]
    desc: "屏幕开关，可用值：开、关"
    siid: 5
    piid: 1
    value_regexp: '/(开|关)/g'
  - name: ["声音开关"]
    desc: "声音开关，可用值：开、关"
    siid: 6
    piid: 1
    value_regexp: '/(开|关)/g'
  - name: ["按键锁定开关"]
    desc: "按键锁定开关，可用值：开、关"
    siid: 7
    piid: 1
    value_regexp: '/(开|关)/g'
  - name: ["最爱模式调节"]
    desc: "调整最爱模式，可用值：0-14
    siid: 8
    piid: 1
    value_regexp: '/([0-9]|1[0-4])/g'
viewable:
  - name: '状态'
    siid: 2
    piid: 1
    unit: ''
  - name: '模式'
    siid: 2
    piid: 2
    unit: ''
  - name: '湿度'
    siid: 3
    piid: 1
    unit: ''
  - name: 'PM2.5浓度'
    siid: 3
    piid: 2
    unit: ''
  - name: '过滤器寿命水平'
    siid: 4
    piid: 1
    unit: ''
  - name: '过滤器使用时间'
    siid: 4
    piid: 2
    unit: ''
  - name: '屏幕状态'
    siid: 5
    piid: 1
    unit: ''
  - name: '声音状态'
    siid: 6
    piid: 1
    unit: ''
  - name: '按键锁定状态'
    siid: 7
    piid: 1
    unit: ''
  - name: '最爱模式等级'
    siid: 8
    piid: 1
    unit: ''`

**Comment by CikeyQi** [comment]
看了一下，你写的没问题，你要将文件重命名为 `zhimi.airpurifier.ma2.yaml` ，再保存到 **/adapter** 文件夹里面就可以了

**Comment by hnyqwq** [comment]
> 看了一下，你写的没问题，你要将文件重命名为 `zhimi.airpurifier.ma2.yaml` ，再保存到 **/adapter** 文件夹里面就可以了

[MiaoYz][21:28:33.891][ERRO] 【mijia-Plugin v1.0.0】 加载适配器：zhimi.airpurifier.ma2失败
这样肿么办，已经放进去重启了的，是不是某个地方放错了还是没设置啥的（？）
![image](https://github.com/CikeyQi/mijia-plugin/assets/46952765/91a8ae1a-a029-486f-ab69-9c4f2b6257ec)

**Comment by CikeyQi** [comment]
检查一下你的yaml文件格式有没有问题，复制到 `https://www.bejson.com/validators/yaml_editor/` 校验一下格式

**Comment by hnyqwq** [comment]
> 检查一下你的yaml文件格式有没有问题，复制到 `https://www.bejson.com/validators/yaml_editor/` 校验一下格式

OK了，检查出来是第28行没加引号T T，改了后试了下都能成功控制了，感谢大佬！
