### ISSUE TITLE
【意见】加入手动结束命令

### ISSUE THREAD

**Issue by Dnyo666** [CikeyQi/mijia-plugin#4]
希望提供一个命令可以终止参数输入，不然结束不了
加入命令，#结束控制或者其他命令用于手动结束操作，避免反复提交错误参数，我看到了超时后的结束操作，但是没有手动结束，是吗？

**Comment by CikeyQi** [comment]
晚点看看

**Comment by Dnyo666** [comment]
好的，麻烦了
