### ISSUE TITLE
添加到米家APP批量控制/手动控制指令

### ISSUE THREAD

**Issue by ayakasuki** [CikeyQi/mijia-plugin#8]
能不能也有API实现这功能呢？添加到米家APP批量控制/手动控制指令可以用云崽控制？ 例如之前在米家APP 添加的手动控制小爱音箱 自定义指令开空调为给小爱说开制冷模式空调 然后米家首页只显示一个开空调的小按钮 这个小按钮的api不知道能否抓包或找到API列出来然后控制？ 这样可能会有些设备就好控制很多

**Comment by CikeyQi** [comment]
本插件的实现并不是抓包实现的，你可以参考 [小米/米家产品库](https://home.miot-spec.com/) 查看您的小爱音响是否有该功能API实现的相关文档，本插件暂不考虑除此以外的其他的API实现
